apiVersion: v1
kind: Service
metadata:
    name: "pdffielddetectionsvc-2023"
    labels:
        app: "pdffielddetectionsvc-2023"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "pdffielddetectionsvc-2023"