class Box:
    def __init__(self, position):
        self.Position = position
        self.FieldPosition = None
        self.IsHorizontal = False
        self.LeftPadding = 0
        self.RightPadding = 0
        self.Weight = 0
        self.TopElement = None
        self.LineText = None
        self.Prefix = None
        self.PrefixGap = 0
        self.Suffix = None
        self.SuffixGap = 0
        self.HasCentLine = False
        self.CentPositionOffset = 0
        self.HasComboLine = False
        self.Combo = 0
        self.FieldCode = None
        self.IsMarkupField = False